apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: karthik.manmohan1285@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - selector:
        dnsZones:
          - "zsdevops01.store"
      dns01:
        route53:
          region: us-east-1
          accessKeyID: AKIA5T3B5YF67JBLLROB
          secretAccessKeySecretRef:
            name: acme-route53
            key: secret-access-key
